## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Deploy microservices based game in Oracle Cloud Infrastructure (OCI) "
    stackDescription: "Powered by OKE, ADB, Java and Redis"
    schemaVersion: 1.0.0
    version: "20230425"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - region
      - release
      - campaign
      - instance_os
      - linux_os_version
      # - INSTALL_HOME
      # - install_jdk11
      # - freeform_tags
      # - instance_ad_number
      # - instance_count
      # - instance_state
      # - cloud_agent_plugins
      # - source_type
      # - boot_volume_backup_policy
      # - block_storage_sizes_in_gbs
      # - assign_public_ip
      # - public_ip

    - title: Required Configuration 
      visible: true  
      variables:
      - compartment_ocid
      - availablity_domain_name
      - show_advanced

    - title: OKE Configuration
      visible: 
          and:
            - show_advanced
      variables:
      - VCN-CIDR
      - OKE_LB_Subnet-CIDR
      - OKE_API_EndPoint_Subnet-CIDR
      - OKE_NodePool_Subnet-CIDR
      - cluster_kube_config_token_version
      - cluster_options_kubernetes_network_config_pods_cidr
      - cluster_options_kubernetes_network_config_services_cidr
      - kubernetes_version
      - cluster_name
      - node_pool_size
      - node_pool_shape
      - node_pool_flex_shape_memory
      - node_pool_flex_shape_ocpus

    - title: "Autonomous Database Provisioning"
      visible: true  
      variables:
      - create_database
      - ADB_NAME
      - IS_FREE_TIER
      - autonomous_database_type
      - autonomous_database_cpu_core_count
      - autonomous_database_data_storage_size_in_tbs
      - database_compartment
      - database

    - title: "Database Configuration"
      visible: true  
      variables:
      - ADMIN_PASSWORD
      - APEX_WORKSPACE
      - DB_USER
      - DB_SCHEMA
      - DB_PASSWORD

    variables:

      show_advanced:
        type: boolean
        title: "Show advanced options?"
        description: "Shows advanced options."
        visible: true
        default: false
      
      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."

      availablity_domain_name:
        type: oci:identity:availabilitydomain:name
        required: true
        visibile: true
        title: "Availability Domain to be chosen"
        description: "Availability Domain to be chosen"
        dependsOn:
          compartmentId: ${compartment_ocid}

      # Optional Configuration     

      IS_FREE_TIER:
        type: boolean
        title: "ATP Free Tier"
        required: true
        default: true
        visible:
          create_database

      ADB_NAME:
        type: string
        title: "Database Name"
        required: true
        default: "f1simdb"
        visible:
          create_database

      ADMIN_PASSWORD:
        type: password
        title: "ADMIN User Password - leave blank if random password is preferred"
        required: false
        visible: true
        default: "W3lc0m3SIM123!#"

      APEX_WORKSPACE:
        type: string
        title: "APEX Workspace (for F1SIM)"
        required: true
        visible: true
        default: "LIVELAPS"

      DB_SCHEMA:
        type: string
        title: "Database Schema (for F1SIM)"
        required: true
        visible: true
        default: "SIMUSER"

      DB_USER:
        type: string
        title: "Database User (for F1SIM)"
        required: true
        visible: true
        default: "SIMUSER"

      DB_PASSWORD:
        type: password
        title: "Database Password (for Database User) - leave blank if random password is preferred"
        required: false
        visible: true
        default: "W3lc0m3SIM123"

      package_install:
        type: string
        title: "Package Install"
        required: true
        visible: true
        default: "f1-simulator-cloud/f1-simulator-cloud-v5_0_0-1.tar.gz"

      package_baseurl:
        type: string
        title: "Package Repo URL"
        required: true
        visible: true
        default: "https://rooms.opcvr.com/packages/"

      customer_contacts:
        type: string
        title: "Customer Contact"
        required: true
        visible: true
        default: "demo@withoracle.cloud"

      INSTALL_HOME:
        type: string
        required: true
        visible: false
        default: "."

      autonomous_database_cpu_core_count:
        type: integer
        default: 1
        minimum: 1
        maximum: 64
        title: "Autonomous Database OCPU"
        description: ""
        visible:
          and:
            - not:
              - IS_FREE_TIER
            - create_database

      autonomous_database_data_storage_size_in_tbs:
        type: integer
        default: 1
        minimum: 1
        maximum: 10
        title: "Autonomous Database Storage (TB)"
        description: ""
        visible:
          and:
            - not:
              - IS_FREE_TIER
            - create_database

      create_database:
        title: "Create New Database?"
        type: boolean

      database_compartment:
        type: oci:identity:compartment:id
        title: "Autonomous Database Compartment"
        required: false
        visible:
          not:
            - create_database

      database:
        type: oci:database:autonomousdatabase:id
        title: "Use Existing Autonomous Database"
        required: false
        dependsOn:
          compartmentId: ${database_compartment}
        visible:
          not:
            - create_database

      autonomous_database_type:
        type: enum
        title: "Workload Type"
        default: "OLTP"
        # enumerated values
        enum:
          - OLTP
          - DW
          - AJD
        visible:
          create_database


      VCN-CIDR:
        type: string
        visible: true
        required: false
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        title: "VCN CIDR"
        description: "Choose VCN CIDR for your OKE deployments."
        default: "10.0.0.0/16"

      OKE_LB_Subnet-CIDR:
        type: string
        visible: true
        required: false
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        title: "OKE LB Subnet CIDR"
        description: "Choose OKE LoadBalancer Subnet CIDR."
        default: "10.0.10.0/24"

      OKE_API_EndPoint_Subnet-CIDR:
        type: string
        visible: true
        required: false
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        title: "OKE API EndPoint Subnet CIDR"
        description: "Choose OKE API EndPoint Subnet CIDR."
        default: "10.0.20.0/24"

      OKE_NodePool_Subnet-CIDR:
        type: string
        visible: true
        required: false
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        title: "OKE NodePool Subnet CIDR"
        description: "Choose OKE NodePool Subnet CIDR."
        default: "10.0.30.0/24"

      cluster_kube_config_token_version:
        type: enum
        visible: true
        required: false
        title: "OKE Cluster Kube Config Token Version"
        description: "Choose OKE Cluster Kube Config Token Version."
        default: "2.0.0"
        enum:
          - "2.0.0"
      
      cluster_options_kubernetes_network_config_pods_cidr:
        type: string
        visible: true
        required: false
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        title: "OKE PODs CIDR"
        description: "Choose OKE PODs CIDR."

      cluster_options_kubernetes_network_config_services_cidr:
        type: string
        visible: true
        required: false
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        title: "OKE Services CIDR"
        description: "Choose OKE Services CIDR."

      kubernetes_version:
        type: enum
        visible: true
        required: false
        title: "Kubernetes Version"
        description: "Choose Kubernetes Version."
        default: "v1.20.11"
        enum:
          - "v1.20.11"
          - "v1.20.8"
          - "v1.19.15"
          - "v1.19.12"
          - "v1.19.7"          
          - "v1.18.10"  

      cluster_name:
        type: string
        visible: true
        required: false
        title: "OKE Cluster Name"
        description: "Choose OKE Cluster Name."

      node_pool_size:
        type: number
        required: false
        minimum: 2
        maximum: 32768
        multipleOf: 1
        default: 3
        title: "OKE NodePool size"
        description: "Choose size of the OKE NodePool."

      node_pool_shape:
        type: oci:core:instanceshape:name
        required: false
        title: "Shape for OKE NodePool"
        description: "Choose shape for compute instances in OKE NodePool."
        default: "VM.Standard.E4.Flex"
        dependsOn:
          compartmentId: ${compartment_ocid}      

      node_pool_flex_shape_ocpus:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 1
        title: "Flex Shape OCPUs"
        description: "Choose number of OCPUs for Flex Shape."
        visible:
          and:
            - or:
              - eq:
                - node_pool_shape 
                - "VM.Standard.E3.Flex"
              - eq:
                - node_pool_shape 
                - "VM.Standard.E4.Flex"
              - eq:
                - node_pool_shape
                - "VM.Optimized3.Flex"
              - eq:
                - node_pool_shape
                - "VM.Standard.A1.Flex"

      node_pool_flex_shape_memory:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 10
        title: "Flex Shape Memory (GB)"
        description: "Choose number GB for Flex Shape Memory."
        visible:
          and:
            - or:
              - eq:
                - node_pool_shape 
                - "VM.Standard.E3.Flex"
              - eq:
                - node_pool_shape
                - "VM.Standard.E4.Flex"
              - eq:
                - node_pool_shape
                - "VM.Optimized3.Flex"  
              - eq:
                - node_pool_shape
                - "VM.Standard.A1.Flex"
                
      release:
        type: string
        required: false
        visible: false
        title: "Reference Architecture Release (OCI Architecture Center)"

      campaign:
        type: string
        required: false
        visible: false
        title: "Reference Architecture Campaign (OCI Architecture Center)"

    outputs:

      generated_ssh_private_key:
        title: "Generated SSH Private Key"
        displayText: "Generated SSH Private Key"
        type: copyableString
        visible: true